sample_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #一見、todolistsが重複しているように見えるが注視すると、HTTPメソッドとURLが完全に一致しているものは一つもない
  get 'todolists/new'=> 'todolists#new'
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolist/:id' => 'todolists#destroy', as: 'destroy_todolist'

end

sample_app/app/models/list.rb
class List < ApplicationRecord
  attachment :image

  validates :title, :body, presence: true

end

sample_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

sample_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController

  def new
    # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。これが、new.htmlファイルのform_withに渡される。
    @list = List.new
  end

  def create
    # 1 . データを新規登録するためのインスタンス作成
    @list = List.new(list_params)
    # 2 . データをデータベースに保存するためのsaveメソッド実行
   if @list.save
    # 3 . 投稿画面へリダイレクト
     flash[:notice] = "successfully!"
     redirect_to todolist_path(@list.id)
   else
     flash[:alert] = "no"
     render action: :new
   end
  end

  def index
    puts "作成したキー #{ENV['SECRET_KEY']}"

    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
     flash[:notice] = "successfully!"
     redirect_to todolist_path(@list.id)
   else
     flash[:alert] = "no"
     render action: :edit
   end
  end

  def destroy
    list = List.find(params[:id]) # データ（レコード）を１件取得
    list.destroy # データ（レコード）を削除
    redirect_to todolists_path #投稿一覧画面へリダイレクト
  end



    private
    # ストロングパラメータ
    def list_params
      params.require(:list).permit(:title, :body, :image)

    end

 end

sample_app/app/helpers/homes_helper.rb
module HomesHelper
end

sample_app/app/helpers/todolists_helper.rb
module TodolistsHelper
end

sample_app/app/views/homes/top.html.erb
<head>
  <link href="../assets/stylesheets/top.css" rel="stylesheet">
</head>

<main>
<h2>投稿ページ</h2>

<content>
  <p>こちらでは、皆様の感動や喜び<br>
     あるいは、日常の中で思い浮かんだ些細な出来事や発見など<br>
     皆様の心に残ったことをご自由に投稿してください。<br>
  </p>
  <p>皆様からの応募お待ちしております。</p>
</content>

</main>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">

  </head>

  <body>
    <header>
      <h1 class="headline"> All Lists</h1>
    </header>

    <nav>
      <ul class="nav-list">
         <li class="nav-list-item">
           <%= link_to "Top", top_path %>
         </li>

       <li class="nav-list-item">
         <%= link_to "Todolists", todolists_path %>
       </li>
       <li class="nav-list-item">
         <%= link_to "New List", todolists_new_path %>
       </li>
      </ul>
     </nav>
    <main>

    

    </main>
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>

    <%= yield %>

  </body>
</html>

sample_app/app/views/todolists/edit.html.erb
<hi>編集画面</hi>
<%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
<div class="edit-font">
 <h4>タイトル</h4>
 <%= f.text_field :title %>
 <h4>本文</h4>
 <%= f.text_area :body %>
 <%= f.submit '保存' %>
</div>
<% end %>

sample_app/app/views/todolists/index.html.erb
<div class-"list-wrap">
 <% @lists.each do |list| %>
  <div class="list-box">
   <%= attachment_image_tag list, :image, :fill, 200, 200, format: 'jpeg' %>
   <div class="list-comment">
    <span class="list-body"><%= list.body %></span>  <!-- ここのspanタグはCSSで編集をしやすくするため -->
    <span class="list-title"><%= link_to list.title, todolist_path(list.id) %></span>
   </div>
  </div>
 <% end %>
</div>

sample_app/app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- form_with部分 -->
<%= form_with model: @list, url:'/todolists', local:true do |f| %> <!-- このビューファイルはtodolistsコントローラと紐づけ -->
<div class="new-font">
  <h4>タイトル</h4>
  <%= f.text_field :title %>  <!-- この部分はフォーム入力のための枠組みとして表示 -->
  <h4>本文</h4>
  <%= f.text_area :body %>    <!-- この部分はフォーム入力のための枠組みとして表示 -->
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <%= f.submit '投稿' %>
</div>
<% end %>

sample_app/app/views/todolists/show.html.erb
<div class="show-font">
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文
<p><%= @list.body %></p>
<h2>画像</h2>
 <%= attachment_image_tag @list, :image, :fill, 300, 300, format: 'jpeg' %>
</div>


<%= link_to "編集", edit_todolist_path(@list.id) %>
<%= link_to "削除", destroy_todolist_path(@list.id), method: :delete, data: { confirm: '削除を実行しますか？', commit: '削除', cancel: 'キャンセル'  } %>